//i need to implement class importLines that will take path to file containing three txt files vehicle.txt, places.txt and lines.txt. I will read these files and create objects of class Line, Place and Vehicle. I will also need to implement a method that will return a list of all lines with their respective stops and vehicles.
expected format fot files:
// vehicle txt
there will be header starting with ### and description of file fromat
then on each line there will be parametrs of each instance of vehicle type, model, capacity, optionaly history in form of string thez will be separated by ,
same format folows for places with id, name, coordinate
and lines